#!/usr/bin/env bash

set -e # Quit on any error.

[ -z "$1" ] && echo "Route not given." && exit 1

AWS_EB_ENV=$1

eb setenv -e ${AWS_EB_ENV} \
USE_IN_MEMORY_DATABASE=false \
MIGRATE_DATABASE_AT_STARTUP=false \
SENTRY_RELEASE=${CI_BUILD_REF}

eb deploy ${AWS_EB_ENV} --staged