name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: |
          ./gradlew distZip --no-daemon
          unzip -o rest-api/build/distributions/rest-api-1.0.0.zip
      - run: flyctl deploy --remote-only
