name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: |
          ./gradlew distZip --no-daemon
          unzip -o rest-api/build/distributions/rest-api-1.0.0.zip

      - name: Build, tag, and push image to Amazon ECR and re-deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker build -t public.ecr.aws/i7z1j0f7/nobt-io/api:latest .
          docker push public.ecr.aws/i7z1j0f7/nobt-io/api:latest
          aws apprunner start-deployment --service-arn arn:aws:apprunner:eu-west-1:450730626438:service/nobt-io-api/cca90ae4610f40bfa7ce2c84f4214f7e --region eu-west-1
